### ISSUE TITLE
java.lang.OutOfMemoryError: Failed to allocate a 104325132 byte allocation with 1048576 free bytes and 95MB until OOM

### ISSUE THREAD

**Issue by 89Jockin** [githubwing/CustomBehavior#3]
Process: com.wingsofts.custombehavior, PID: 5194
                                                 java.lang.OutOfMemoryError: Failed to allocate a 104325132 byte allocation with 1048576 free bytes and 95MB until OOM
                                                     at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                                                     at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
                                                     at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:609)
                                                     at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:444)
                                                     at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:1080)
                                                     at android.content.res.Resources.loadDrawableForCookie(Resources.java:2635)
                                                     at android.content.res.Resources.loadDrawable(Resources.java:2540)
                                                     at android.content.res.TypedArray.getDrawable(TypedArray.java:870)
                                                     at android.widget.ImageView.<init>(ImageView.java:152)
                                                     at android.widget.ImageView.<init>(ImageView.java:140)
                                                     at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:57)
                                                     at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:53)
                                                     at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:106)
                                                     at android.support.v7.app.AppCompatDelegateImplV7.createView(AppCompatDelegateImplV7.java:972)
                                                     at android.support.v7.app.AppCompatDelegateImplV7.onCreateView(AppCompatDelegateImplV7.java:1031)
                                                     at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:746)
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
                                                     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
                                                     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
                                                     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                     at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:276)
                                                     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                                                     at com.wingsofts.custombehavior.MainActivity.onCreate(MainActivity.java:12)
                                                     at android.app.Activity.performCreate(Activity.java:6237)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                     at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:148)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by githubwing** [comment]
my bad.  this demo is not perfect. you can replace some image..
